minimumReleaseAge: 2880

packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.28.0
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^9.28.0
  eslint-plugin-boundaries: ^5.0.1
  eslint-plugin-check-file: ^3.0.1
  globals: ^16.2.0
  prettier: ^3.8.3
  react: ^19.2.5
  react-dom: ^19.2.5
  tsup: ^8.5.0
  turbo: ^2.9.6
  typescript: 6.0.2
  typescript-eslint: ^8.33.1
  vitest: ^4.1.4

onlyBuiltDependencies:
  - esbuild
