packages:
  - apps/*
  - packages/*

catalog:
  "@commitlint/cli": 21.0.1
  "@commitlint/config-conventional": 21.0.1
  "@eslint/js": ^10.0.0
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  "@types/node": ^25.7.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^10.0.0
  eslint-plugin-boundaries: ^6.0.0
  eslint-plugin-check-file: ^3.0.1
  globals: ^17.0.0
  husky: ^9.1.7
  prettier: ^3.8.3
  react: ^19.2.5
  react-dom: ^19.2.5
  tsup: ^8.5.0
  tsx: ^4.21.0
  turbo: ^2.9.6
  typescript: 6.0.3
  typescript-eslint: ^8.33.1
  vitest: ^4.1.4
minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - vite
  - rolldown
  - "@rolldown/*"
  - "@rolldown/binding-linux-x64-gnu"
  - rolldown-plugin-dts
  - tsx

onlyBuiltDependencies:
  - esbuild
  - rolldown

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux
