import {
	AppWindow,
	ArrowBendUpRight,
	ArrowsClockwise,
	BookOpen,
	BracketsCurly,
	CloudArrowUp,
	Code,
	Compass,
	CursorClick,
	Database,
	Download,
	Drop,
	FileCode,
	FileHtml,
	FileMagnifyingGlass,
	FileX,
	Function,
	Gear,
	Globe,
	House,
	Layout,
	Lightning,
	ListChecks,
	Package,
	Path,
	Plugs,
	PuzzlePiece,
	Question,
	Rocket,
	ShieldWarning,
	Signpost,
	Swap,
	Terminal,
	TreeStructure,
	Warning,
} from "@phosphor-icons/react";
import type { ReactNode } from "react";

const iconMap: Record<string, ReactNode> = {
	rocket: <Rocket />,
	download: <Download />,
	lightning: <Lightning />,
	compass: <Compass />,
	book: <BookOpen />,
	code: <Code />,
	brackets: <BracketsCurly />,
	question: <Question />,
	checklist: <ListChecks />,
	signpost: <Signpost />,
	layout: <Layout />,
	arrows: <ArrowsClockwise />,
	drop: <Drop />,
	plugs: <Plugs />,
	warning: <Warning />,
	gear: <Gear />,
	cloud: <CloudArrowUp />,
	appwindow: <AppWindow />,
	function: <Function />,
	file: <FileMagnifyingGlass />,
	filecode: <FileCode />,
	filex: <FileX />,
	puzzle: <PuzzlePiece />,
	throw: <ArrowBendUpRight />,
	swap: <Swap />,
	terminal: <Terminal />,
	package: <Package />,
	filehtml: <FileHtml />,
	path: <Path />,
	cursor: <CursorClick />,
	database: <Database />,
	globe: <Globe />,
	house: <House />,
	shield: <ShieldWarning />,
	tree: <TreeStructure />,
};

export function resolveIcon(icon: string | undefined): ReactNode | undefined {
	if (!icon) return undefined;
	return iconMap[icon];
}
